//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA_Hire_Disk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disks
    {
        public int Id_Disk { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Image { get; set; }
        public string Publisher { get; set; }
        public string Developer { get; set; }
        public string Category { get; set; }
        public string Language_Interface { get; set; }
        public string Language_Voice { get; set; }
        public string Year_Manufacture { get; set; }
        public string Info { get; set; }
        public Nullable<long> Hire { get; set; }
    }
}
